import { Oswald, Poppins } from "next/font/google";
import "../globals.css";
import Navbar from "../../component/Navbar";

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
  weight: ["400", "700"], // You can load multiple weights
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "600"], // Add the weights you plan to use
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${oswald.variable} ${poppins.variable} font-sans bg-gray-100 min-h-screen`}
      >
        <Navbar />
        {/* <h1 className=" --font-oswald">This is from main layout</h1> */}
        {children}
      </body>
    </html>
  );
}
