import "./globals.css";
import { Oswald, Poppins } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/ThemeProvider";
import Navbar from "../component/Navbar";
import Sidebar from "@/components/Sidebar";
const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
  weight: ["400", "700"],
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "600"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${oswald.variable} ${poppins.variable} font-sans min-h-screen`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <header className="flex items-center gap-4 p-4 border-b border-border bg-background">
            <Sidebar />
            
            <h1 className="text-xl font-bold text-foreground">My Website</h1>
          </header>
            <Toaster position="top-right" />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
