import "./globals.css";
import { Oswald, Poppins } from "next/font/google";
import Navbar from "../component/Navbar";
import Sidebar from "@/components/Sidebar";
const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
  weight: ["400", "700"],
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "600"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${oswald.variable} ${poppins.variable} font-sans bg-gray-100 min-h-screen`}
      >
        <Navbar />
        <header className="flex items-center gap-4 p-4 border-b">
          <Sidebar />
          <h1 className="text-xl font-bold">My Website</h1>
        </header>
        {children}
      </body>
    </html>
  );
}
